---
  - name: Install ufw
    apt: name=ufw

  - name: Allow ssh through firewall
    ufw: proto=tcp port=22 rule=allow

  - name: Set ufw policy
    ufw: state=enabled direction=incoming policy=deny

  - name: Allow connection from app1 server
    ufw: rule=allow proto=tcp src={{app1_server}} port=3306
