---
instance_type: t2.micro
security_group: SG-app1 # Change the security group name here
image: ami-21d30f42 # Change the AMI, from which you want to launch the server
region: ap-southeast-1 # Change the Region
keypair: browserstack # Change the keypair name
vpc_subnet_id: subnet-0bbe306e
volumes:
- device_name: /dev/sda1
  volume_size: 50
  delete_on_termination: false
count: 1
